# Generated by Django 5.2.11 on 2026-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('student_class', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
